### ISSUE TITLE
xfreerdp

### ISSUE THREAD

**Issue by Stepman123** [maaaaz/patator-windows#1]
C:\patator-windows-master>patator-windows rdp_login --help
ERROR: xfreerdp 1.2.0-beta1 (https://github.com/FreeRDP/FreeRDP.git) is required to run rdp_login.
Please read the README inside for more information.

How to use with wfreerdp? https://cloudbase.it/freerdp-for-windows-nightly-builds/

**Comment by maaaaz** [comment]
I know. I'll see if I can embed it in a future release.
Cheers

**Comment by Stepman123** [comment]
wfreerdp.dll http://my-files.ru/b4r0xi
wfreerdp-client.dll http://my-files.ru/c345xr
This should help

**Comment by Stepman123** [comment]
wfreerdp.dll http://my-files.ru/b4r0xi
wfreerdp-client.dll http://my-files.ru/c345xr
This should help

**Comment by MBillar** [comment]
Can u fix it? I have the same problem

**Comment by maaaaz** [comment]
I had looked how to integrate it few months ago but I couldn't find an easy way.
Maybe in the future.

**Comment by ploinkploink** [comment]
hello!
you write to check the readme for information about how to integrate xfreerdp but there is nothing there..
it just gives the git url which is an uncompiled project
so how to integrate it? a bit of information would be great!
