### ISSUE TITLE
Not working for windows 10?

### ISSUE THREAD

**Issue by isgalvez24** [maaaaz/patator-windows#3]
Hi, today i just decided to test patator, but when i had everything ready to work with it i saw that this was happening.

I open CMD, cd to the patator directory and run it, after this i execute this console comand:
patator.exe http_fuzz url="http://localhost/phpmyadmin/index.php" method=POST body='pma_username=root&pma_password=FILE00&server=1&target=index.php' 0=passwords.txt follow=1 accept_cookie=1 -x ignore:fgrep='Cannot log in to the MySQL server'

This is what the console return to me:

16:09:23 patator INFO - Starting Patator v0.7-beta (https://github.com/lanjelot/patator) at 2017-08-11 16:09 Hora de verano romance 16:09:23 patator INFO - 16:09:23 patator INFO - code size:clen time | candidate | num | mesg 16:09:23 patator INFO - ----------------------------------------------------------------------------- 16:09:24 patator INFO - 200 96627:-1 0.391 | | 1 | HTTP/1.1 200 OK 16:09:24 patator INFO - Hits/Done/Skip/Fail/Size: 1/1/0/0/1, Avg: 0 r/s, Time: 0h 0m 1s "pma_password" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable. "server" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable. "target" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.

If we translate the spanish part, it say that pma_password, server and target are not recognized as a internal or external command.

What is happening? How can i make it work well?

I downloaded the patator already compiled from here.

I am using windows 10 pro.
Thanks!

**Comment by maaaaz** [comment]
Hello,

I managed to reproduce that bug and debug it with the patator `-d` option but it is related to Windows batch interpreter escape:
```
> patator.exe http_fuzz -d url='http://google.fr' method=POST body='pma_username=root&pma_password=FILE0&server=1&target=index.php' 0=passwords.txt follow=1 accept_cookie=1 -x ignore:fgrep='Cannot log in to the MySQL server'
20:59:50 patator   DEBUG [MainProcess] k: url, v: 'http://google.fr'
20:59:50 patator   DEBUG [MainProcess] k: method, v: POST
20:59:50 patator   DEBUG [MainProcess] k: body, v: 'pma_username=root
20:59:50 patator   DEBUG [MainProcess] kargs: [('url', "'http://google.fr'"), ('method', 'POST'), ('body', "'pma_username=root")]
20:59:50 patator   DEBUG [MainProcess] iter_vals: []
20:59:50 patator   DEBUG [MainProcess] iter_keys: {}
20:59:50 patator   DEBUG [MainProcess] enc_keys: []
20:59:50 patator   DEBUG [MainProcess] payload: {'url': "'http://google.fr'", 'body': "'pma_username=root", 'method': 'POST'}
```
You can see that the `body` option only contains `'pma_username=root`, everything after the original `&` character have been ditched by the batch interpreter and considered as [another command](https://stackoverflow.com/a/35578027).

Put double quotes or prefer using a Powershell interpreter:
```
> patator.exe http_fuzz -d url="http://google.fr" method=POST body="pma_username=root&pma_password=FILE0&server=1&target=index.php" 0=passwords.txt follow=1 accept_cookie=1 -x ignore:fgrep="Cannot log in to the MySQL server"
21:01:54 patator   DEBUG [MainProcess] k: url, v: http://google.fr
21:01:54 patator   DEBUG [MainProcess] k: method, v: POST
21:01:54 patator   DEBUG [MainProcess] k: body, v: pma_username=root&pma_password=FILE0&server=1&target=index.php
21:01:54 patator   DEBUG [MainProcess] k: 0, v: passwords.txt
21:01:54 patator   DEBUG [MainProcess] k: follow, v: 1
21:01:54 patator   DEBUG [MainProcess] k: accept_cookie, v: 1
21:01:54 patator   DEBUG [MainProcess] kargs: [('url', 'http://google.fr'), ('method', 'POST'), ('body', 'pma_username=root&pma_password=FILE0&server=1&target=index.php'), ('follow', '1'), ('accept_cookie', '1')]
21:01:54 patator   DEBUG [MainProcess] iter_vals: ['passwords.txt']
21:01:54 patator   DEBUG [MainProcess] iter_keys: {0: ('FILE', 'passwords.txt', ['body'])}
21:01:54 patator   DEBUG [MainProcess] enc_keys: []
21:01:54 patator   DEBUG [MainProcess] payload: {'url': 'http://google.fr', 'body': 'pma_username=root&pma_password=FILE0&server=1&target=index.php', 'accept_cookie': '1', 'method': 'POST', 'follow': '1'}
21:01:54 patator   DEBUG [MainProcess] actions: {'ignore': [([['fgrep', 'Cannot log in to the MySQL server']], None)]}
```
You can see here that the `body` option has everything right.

Cheers.
